name: Build Android APK

on:
  workflow_dispatch: # 允许你手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build Debug APK
        run: |
          # 给 gradlew 执行权限
          chmod +x ./gradlew
          # 编译 Debug 版 APK
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LiquidGlass-debug
          path: app/build/outputs/apk/debug/*.apk
